### ISSUE TITLE
Create Player Inventory That Utilizes Interfaces & Uses Only 1 List

### ISSUE THREAD

**Issue by MaxCaytonFTCC** [MaxCaytonFTCC/Whispers#27]
This will work best once the Inheritance Issue is completed because of the upcoming "Item" parent class.

**Comment by mccroarK** [comment]
Closed: 10/2/2023
Changed Room, Mob, and Player inventories to use Usable abstract class

Issues:
Still need to test Room's info methods to see if they work with the new format.
